### ISSUE TITLE
No Documentation

### ISSUE THREAD

**Issue by Johnrobmiller** [thednp/bezier-easing#11]
I see several methods on the CubicBezier class, and they all have cryptic, non-descript names such that it is impossible to guess what they do. However, there is no documentation explaining what they do.

If you don't want people to use the methods on these classes, then it would be better to not include them rather than give them cryptic names and fail to document what they do.

**Comment by thednp** [comment]
Thanks for the heads up :+1: 

This library doesn't need any documentation, you basically use the exported easing function as configured, all its methods are internally used.
